---
- name: Cambio de hora
  hosts: appservers-group

  tasks:
  - name: Verificar zona horaria original
    command: timedatectl
    register: old_timezone

  - name: Enable JBoss to be started at boot
    service: 
      name=jboss
      state=stopped

  - name: Ver zona horaria
    debug: 
      var: old_timezone
  #- name: Bajar Servicios
  - name: Actualizar paquetes
    yum:
      name: tzdata
      state: latest

  - name: Dejar la zona en Santiago 
    timezone:
      name: "America/Santiago"

  - name: Verificar nueva zona horaria
    command: timedatectl
    register: new_timezone

  - name: Ver zona horaria
    debug: 
      var: new_timezone

  - name: Enable JBoss to be started at boot
    service: 
      name=jboss
      state=started
  
     #- name: Subir Servicios
