---
- name: Reset de zona horaria
  hosts: appservers-group

  tasks:
  - name: Verificar zona horaria original
    command: timedatectl
    register: old_timezone

  - name: Ver zona horaria
    debug: 
      var: old_timezone

  - name: Actualizar paquetes
    yum:
      name: http://linuxsoft.cern.ch/cern/centos/7/updates/x86_64/Packages/tzdata-2016d-1.el7.noarch.rpm
      state: present

  - name: Dejar la zona en UTC 
    timezone:
      name: "UTC"

  - name: Verificar nueva zona horaria
    command: timedatectl
    register: new_timezone

  - name: Ver zona horaria
    debug: 
      var: new_timezone

     #- name: Subir Servicios
